directories:
  tasks_dir: "tasks"
  archive_dir: "archive"
  test_tasks_dir: "tests/test_tasks"
  test_archive_dir: "tests/test_archive"

statuses:
  - "To Do"
  - "In Progress"
  - "Blocked"
  - "Complete"
  - "Archived"

export_files:
  csv: "tasks_export.csv"
  json: "tasks_export.json"
  yaml: "tasks_export.yaml"

defaults:
  priority: 0
  description: "No description"
  due_date: "No due date"
  tags: ""
  status: "To Do"


table:
  columns:
    - name: "Task Name"
      max_length: 30

    - name: "Priority Score"
      max_length: 52

    - name: "Status"
      max_length: 15

    # - name: "Description"
    #   max_length: 30

    - name: "Tags"
      max_length: 30


ms_todo:
  token: "EwBoBMl6BAAUBKgm8k1UswUNwklmy2v7U/S+1fEAAVNoQHmIl1/wak09EmiNqjFl8Cbp1Bw7yim2I4byYYuuiobRG79opWnuVy4+X23rExHQOpCmb4SzE3kxw+d5LkSGwWJtRvh/YJXWSb352PwLAX1C+aJjQGHBWfKnSGhxUEdh8BJJfig3RSj81wdJwjO+RIjVxwiFgCCEXj+c9SE1y6kPscLYmVGtBTw5OhyYOxLLgnHezm04Wr5LltaYpQ/ic/Q/GzEbIEkcy8C29WeTEZdvHk/ZRP478FG1xsM80Z2YKjNq9Odnw8vUuxYqDg2ZMvdgAXM3cNjeCxclSFsYE+CcjujhZElK1Z8s3Argoks3N9rLegh0giuO5AKxJLsQZgAAEAnUpRxR+C7NZ9WuwuFn+5owAwiTWaeTsgCrDTJq6URm7q5BC3GHchjijj0u22GcU70QMzO+hrYhDbN7g9i/rSL6P03EiIixMenDUCJudcBLdvYpNCDGNk4EkJCyhAddu18ge7Ss7Go2/GW35rT943GQ7z18d/SKBJir+9inSN15/XMKxGfkWXcuVDaZJNFLwPngLROxqAlWBvK++N4Hj1qGOp0SIjqzU7Ug6lwoBQjtHlFskENHxLDA4FsOG1c06wzff99LdcVKE4mNJ0KVStzEkfNnhjJAQ9uatjYN07a3xF/eIwrEgZLDtM5k153oEOO2ZI2D+Reid3s46f6tPQYbIkDSLnSVGaUiGs8YGS/1sN4D11DmaQbMrApXA5Jh4N7JZoPqvhvLwN4AeOMszeoZzF78ukxLxO7sMu2oD2TxGf8az9uKFQ5ewi7a3jfSm28FO3pGu7uhYv+DBbY3hl0rys4oMmjAld1S2oa0B66oY+Gid8YPIyGdTj8AoOWhE6mDNCrAA7swroVAgBa4Cz/7cIIpPGbZ+9q1HqXrQ8E5P2pttUJpmnDGXTmA1jmd7XRo6lCaZTB8nm46aqQrh/aLui4ToRywa6eGPJ8Il8QgWC01JZ39U6YXqVrse4tU8Q42+gVBD8GD6n09B4G8P3N4baf/c/IkNqv2G4nXONK3ldJ8pmbCjr9/br0u5dPiH96gHJRQ0cmcTV0F6tSPgMxnTKKmNjDcEhEgHkIB03t9g1oyfZJsGB6ka4NutkrlPd+JYaQF61WU2jf7LAREVWVBlB7ZHMnffSveCTfSCt1QbXLJ5SvAJTxfg75VZsssvqyCHY+uu4rnvTua5THBcvEeK8Wy9oRv2iou6KJaeYLNL57nYuL10+p7PqoQSDSVDWf/5SA4mMbNC5Gvzf+3GuHS1QtA6CUNsAtc/HfLKA/O0++VU5+GzUV8ghy5h9BWP+g72vKLibGqpftPrMFsuWS3pkovCcjUzOnrvM+YGqGavIIjFsjv2rzCwfOnuNoq7G/pf8i/Nv9OXxQAWy6qNrBbAJJX0wWXi0Piu7Tcy9rM4Tlj3VNfbKxO4ElMSPz57CyGj54lnND0VNzUfyZ3RQd6vXoD"


gantt:
  height: 800
